### ISSUE TITLE
Remove the need of MY_BRANCH

### ISSUE THREAD

**Issue by mahomedalid** [cse-labs/res-edge-labs#10]
## Description

For tracking purposes to solve the comment from @bartr  in here: https://github.com/cse-labs/res-dev/pull/8#discussion_r1158857107

## Expected Behavior

- No mentions of $MY_BRANCH
- flt cluster should find an alternative for the example to create the cluster that maybe takes in consideration multiple users working in the same branch. For example: Use the GITHUB_USER instead.

## Details

Also tracked here https://github.com/cse-labs/Project100k/issues/775

**Comment by madossan01** [comment]
This can be closed as the lab does not contain instructions to create and set mybranch.
